// This file is auto-generated by packages/calmo-ui/scripts/generate-deep-types.mjs
export { Accordion, AccordionItem } from "../index.js";
export type { AccordionProps, AccordionItemProps } from "../index.js";
