// This file is auto-generated by packages/calmo-ui/scripts/generate-deep-types.mjs
export { AgreementModuleTopTitle as default } from "../index.js";
export type { AgreementModuleTopTitleProps } from "../index.js";
