// This file is auto-generated by packages/calmo-ui/scripts/generate-deep-types.mjs
export { Asset as default, AssetContentIcon, AssetContentLottie, AssetLottie, AssetLottieCore } from "../index.js";
export type { AssetNamespace, AssetBaseProps, AssetLottieProps } from "../index.js";
