// This file is auto-generated by packages/calmo-ui/scripts/generate-deep-types.mjs
export { BottomCTADouble as default } from "../index.js";
export type { BottomCTAAction, BottomCTADoubleProps } from "../index.js";
