// This file is auto-generated by packages/calmo-ui/scripts/generate-deep-types.mjs
export { CommandPalette as default } from "../index.js";
export type { CommandItem, CommandPaletteProps } from "../index.js";
