// This file is auto-generated by packages/calmo-ui/scripts/generate-deep-types.mjs
export { FloatButtonAgreementModule as default, FloatButtonAgreementModuleCTA } from "../index.js";
export type { AgreementModuleCTAProps, FloatButtonAgreementModuleProps } from "../index.js";
