// This file is auto-generated by packages/calmo-ui/scripts/generate-deep-types.mjs
export { FullScreenLoader as default } from "../index.js";
export type { FullScreenLoaderProps } from "../index.js";
