// This file is auto-generated by packages/ripple-ui/scripts/generate-deep-types.mjs
export { AgreementModuleTop as default } from "../index.js";
export type { AgreementModuleTopProps } from "../index.js";
