// This file is auto-generated by packages/ripple-ui/scripts/generate-deep-types.mjs
export { AgreementModuleContent as default } from "../index.js";
export type { AgreementModuleContentProps } from "../index.js";
