// This file is auto-generated by packages/ripple-ui/scripts/generate-deep-types.mjs
export { BottomSheetAgreementModule as default, BottomSheetAgreementModuleCTA } from "../index.js";
export type { AgreementModuleCTAProps, BottomSheetAgreementModuleProps } from "../index.js";
