// This file is auto-generated by packages/ripple-ui/scripts/generate-deep-types.mjs
export { FullSecureKeypad as default } from "../index.js";
export type { FullSecureKeypadProps } from "../index.js";
