// This file is auto-generated by packages/ripple-ui/scripts/generate-deep-types.mjs
export { FullPageAgreementModule as default, FullPageAgreementModuleCTA } from "../index.js";
export type { AgreementModuleCTAProps, FullPageAgreementModuleProps } from "../index.js";
