// This file is auto-generated by packages/ripple-ui/scripts/generate-deep-types.mjs
export { GradientBottomSheetAgreementModule as default, GradientBottomSheetAgreementModuleCTA } from "../index.js";
export type { AgreementModuleCTAProps, GradientBottomSheetAgreementModuleProps } from "../index.js";
