// This file is auto-generated by packages/ripple-ui/scripts/generate-deep-types.mjs
export { Paragraph as default, ParagraphIcon } from "../index.js";
export type { ParagraphNamespace, ParagraphProps, ParagraphIconProps } from "../index.js";
