// This file is auto-generated by packages/ripple-ui/scripts/generate-deep-types.mjs
export { Post as default, PostHr } from "../index.js";
export type { PostNamespace, PostProps, PostHrProps } from "../index.js";
